-- Categories
CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Products (Bikes)
CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  image_url VARCHAR(255),
  has_sizes BOOLEAN DEFAULT true,
  available_sizes VARCHAR(255) DEFAULT 'S,M,L,XL',
  features TEXT,
  specs JSONB DEFAULT '{}'::jsonb,
  geometry JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Users
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  role VARCHAR(20) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Orders
CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  total_price NUMERIC(10,2) NOT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Order Items
CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id),
  quantity INTEGER NOT NULL,
  price_at_purchase NUMERIC(10,2) NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Insert default categories
INSERT INTO categories (name, description) VALUES
  ('XC', 'Cross-Country bikes for speed and efficiency'),
  ('Trail', 'Versatile all-purpose trail bikes'),
  ('Downcountry', 'Lightweight descending machines'),
  ('Enduro', 'Long-travel aggressive trail bikes'),
  ('Downhill', 'Gravity-focused extreme downhill bikes')
ON CONFLICT (name) DO NOTHING;

-- Insert sample products
INSERT INTO products (category_id, name, description, price, stock_quantity, image_url) VALUES
  (1, 'Swift XC Pro', 'Lightweight cross-country racer built for speed', 1499.99, 15, '/api/images/1-swift-xc-pro.jpg'),
  (2, 'TrailBlazer Elite', 'Versatile trail bike for all terrain mayhem', 2199.99, 20, '/api/images/2-trailblazer-elite.jpg'),
  (3, 'Alpine Descent', 'Lightweight with big descending capability', 2799.99, 10, '/api/images/3-alpine-descent.jpg'),
  (4, 'Beast Mode 29', 'Long travel aggressive enduro machine for tech', 3499.99, 12, '/api/images/4-beast-mode-29.jpg'),
  (5, 'Gravity King DH', 'Full suspension gravity focused monster truck', 4299.99, 8, '/api/images/5-gravity-king-dh.jpg'),
  (1, 'Cross Lite', 'Budget-friendly cross-country option', 899.99, 25, '/api/images/1-cross-lite.jpg'),
  (2, 'Trailmaster 27.5', 'Perfect 27.5" trail ripper for flow', 1899.99, 18, '/api/images/2-trailmaster-27-5.jpg'),
  (4, 'Enduro Plus', 'Feature-packed enduro workhorse', 3099.99, 14, '/api/images/4-enduro-plus.jpg')
ON CONFLICT DO NOTHING;

-- Create admin user (password: admin123)
INSERT INTO users (email, password_hash, first_name, last_name, role) VALUES
  ('admin@senditcycles.com', '$2a$10$PCcHVwS.8SPme67BvM9r7uztWnq/HSSM.QLPAuGGpG7nitIUwDveu', 'Admin', 'User', 'admin')
ON CONFLICT (email) DO NOTHING;
